[Interface]
PrivateKey = sD3GZzg+92V+YWU+AHSgry6z+JzH33vFTlRyH3i6iEM=
Address    = 10.0.20.11/32

[Peer]
PublicKey           = fKMvP3rJUbgCLnbIn2dUrk08VA9jbFHgCFzWeeiSDj8=
Endpoint            = 10.10.100.1:51820
AllowedIPs          = 172.16.17.0/24,10.0.20.0/24
PersistentKeepalive = 25
