[Interface]
PrivateKey = aAFfwx7+EmBRLND/a1uXYJ2m7SUnsgppKUkXOd2LqX0=
Address    = 10.0.20.40/32

[Peer]
PublicKey           = fKMvP3rJUbgCLnbIn2dUrk08VA9jbFHgCFzWeeiSDj8=
Endpoint            = 10.10.100.1:51820
AllowedIPs          = 172.16.17.0/24,10.0.20.0/24
PersistentKeepalive = 25
