[Interface]
PrivateKey = iLOYJcdw+YkvFutTb4CtYhBPuL8+/6mIWCL4qmjcC2M=
Address    = 10.0.20.23/32

[Peer]
PublicKey           = fKMvP3rJUbgCLnbIn2dUrk08VA9jbFHgCFzWeeiSDj8=
Endpoint            = 10.10.100.1:51820
AllowedIPs          = 172.16.17.0/24,10.0.20.0/24
PersistentKeepalive = 25
