[Interface]
PrivateKey = mIyLCOUyn2p579Mv9hMX0FPYe3jHRhfQhPmr/kOgDm4=
Address    = 10.0.20.100/32

[Peer]
PublicKey           = fKMvP3rJUbgCLnbIn2dUrk08VA9jbFHgCFzWeeiSDj8=
Endpoint            = 10.10.10.9:51820
AllowedIPs          = 172.16.17.0/24,10.0.20.0/24
PersistentKeepalive = 25
