[Interface]
PrivateKey = wCSh2I0bCDhxZkLL88/UHX119DSSi6Av5KV5vj0vz10=
Address    = 10.0.20.36/32

[Peer]
PublicKey           = fKMvP3rJUbgCLnbIn2dUrk08VA9jbFHgCFzWeeiSDj8=
Endpoint            = 10.10.100.1:51820
AllowedIPs          = 172.16.17.0/24,10.0.20.0/24
PersistentKeepalive = 25
